name: Daily DevSync Update [21f3003056@ds.study.iitm.ac.in]

on:
  schedule:
    # Runs every day at 07:05 IST (which is 01:35 UTC). Adjust as needed.
    - cron: '35 1 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Daily Commit by 21f3003056@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-status.log
          git config user.name "DevSyncBot"
          git config user.email "21f3003056@ds.study.iitm.ac.in"
          git add daily-status.log
          git commit -m "Daily automated commit: $(date)" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.myrepoleveltoken }}
